version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 192.0.2.0/24

volumes:
  postgres_data: {}
  redis: {}

services:
  api:
    ports:
      - "3000:3000"
    image: tranact/jpegger_api_app:development
    depends_on:
      - redis
    environment:
      - JPEGGER_HOST=${JPEGGER_HOST}
      - JPEGGER_DATABASE=${JPEGGER_DATABASE}
      - JPEGGER_USERNAME=${JPEGGER_USERNAME}
      - JPEGGER_PASSWORD=${JPEGGER_PASSWORD}
      - JPEGGER_PORT=${JPEGGER_PORT}
      #- APPLICATION_HOST=${APPLICATION_HOST}
      #- APPLICATION_HOST=localhost

  web:
    ports:
      - "3001:3001"
    image: tranact/jpegger_web_app:development
    depends_on:
      - db
      - api
    links:
      - api

  db:
    image: postgres
    expose:
      - "5432"
    environment:
      #- POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jpegger_web_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z

  nginx:
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    image: tranact/jpegger_api_nginx:development

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
